# Generated by Django 3.1 on 2020-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='warehouses',
            field=models.ManyToManyField(blank=True, to='market.WareHouse', verbose_name='warehouses'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='agents',
            field=models.ManyToManyField(blank=True, to='market.Employee', verbose_name='employees'),
        ),
        migrations.DeleteModel(
            name='WareHouseKeeper',
        ),
    ]
