# Generated by Django 3.1 on 2020-09-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200918_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer_shipper',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employer_supplier',
        ),
        migrations.AddField(
            model_name='employee',
            name='introducer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='معرف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('نگهبان', 'نگهبان'), ('مدیر', 'مدیر'), ('فنی', 'فنی'), ('تایید نشده', 'تایید نشده'), ('حسابدار', 'حسابدار'), ('صندوقدار', 'صندوقدار')], default='تایید نشده', max_length=50, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(choices=[('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], default='کارشناسی', max_length=50, verbose_name='مدرک'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رشته تحصیلی'),
        ),
    ]
