# Generated by Django 3.1 on 2020-09-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200917_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='agents',
            field=models.ManyToManyField(blank=True, to='market.Employee', verbose_name='employees'),
        ),
    ]
