# Generated by Django 3.1 on 2020-10-02 17:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20201002_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=5000, null=True, verbose_name='شرح کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True, verbose_name='شرح کوتاه'),
        ),
    ]
