# Generated by Django 3.1 on 2020-10-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_color'),
        ('market', '0007_auto_20201002_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='app.Color', verbose_name='رنگ ها'),
        ),
    ]
