# Generated by Django 3.1 on 2020-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_color'),
        ('market', '0008_auto_20201002_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metadatas',
            field=models.ManyToManyField(blank=True, to='app.MetaData', verbose_name='کلمات کلیدی سئو'),
        ),
    ]
