# Generated by Django 3.1 on 2020-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumbotron',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='شرح کامل'),
        ),
    ]
