# Generated by Django 3.1 on 2020-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200913_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/Tag/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.CharField(default='description', max_length=50, verbose_name='key value'),
        ),
    ]
