# Generated by Django 3.1 on 2020-09-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200913_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='for_home',
        ),
    ]
