# Generated by Django 3.1 on 2020-09-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200915_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountDownItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_origin', models.ImageField(upload_to='app/images/CountDownItem/', verbose_name='تصویر  345*970 ')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('pretitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pre Title')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('counter', models.IntegerField(default=100, verbose_name='شمارنده')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'CountDownItem',
                'verbose_name_plural': 'CountDownItems',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='count_down_items',
            field=models.ManyToManyField(blank=True, to='app.CountDownItem', verbose_name='شمارنده ها'),
        ),
    ]
