# Generated by Django 3.1 on 2020-09-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200918_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countdownitem',
            options={'verbose_name': 'CountDownItem', 'verbose_name_plural': 'شمارنده ها'},
        ),
    ]
