# Generated by Django 3.1 on 2020-09-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200920_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='app/images/OurWorkCategory/', verbose_name='تصویر سربرگ')),
            ],
            options={
                'verbose_name': 'دسته بندی  پروژه',
                'verbose_name_plural': 'دسته بندی  پروژه ها',
            },
        ),
        migrations.AddField(
            model_name='ourwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ourworkcategory', verbose_name='دسته بندی'),
        ),
    ]
