# Generated by Django 3.1 on 2020-09-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200922_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='app/Document', verbose_name='فایل ضمیمه'),
        ),
    ]
