# Generated by Django 3.1 on 2020-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_signature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='app/Document', verbose_name='فایل ضمیمه'),
        ),
    ]
