# Generated by Django 3.1 on 2020-09-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200926_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.profile', verbose_name='profile'),
            preserve_default=False,
        ),
    ]
