# Generated by Django 3.1 on 2020-09-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='url',
        ),
        migrations.AddField(
            model_name='link',
            name='for_nav',
            field=models.BooleanField(default=False, verbose_name='نمایش در منوی بالای سایت'),
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default='#', max_length=2000, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('رنگ متن منوی سایت', 'رنگ متن منوی سایت'), ('تگ سرچ گوگل', 'تگ سرچ گوگل'), ('درباره ما کوتاه', 'درباره ما کوتاه'), ('درباره ما کامل', 'درباره ما کامل'), ('موبایل', 'موبایل'), ('لینک', 'لینک'), ('ایمیل', 'ایمیل'), ('فکس', 'فکس'), ('تلفن', 'تلفن'), ('موقعیت در گوگل مپ', 'موقعیت در گوگل مپ'), ('آدرس', 'آدرس'), ('شرح کوتاه', 'شرح کوتاه'), ('عنوان درباره ما', 'عنوان درباره ما'), ('عنوان', 'عنوان'), ('واحد پول', 'واحد پول'), ('پیش عنوان', 'پیش عنوان'), ('عنوان ویدیو', 'عنوان ویدیو'), ('لینک ویدیو', 'لینک ویدیو'), ('ارتباط با ما', 'ارتباط با ما'), ('کد پستی', 'کد پستی'), ('قوانین', 'قوانین'), ('عنوان تیم ما', 'عنوان تیم ما'), ('لینک تیم ما', 'لینک تیم ما'), ('پیام درخواست نامعتبر', 'پیام درخواست نامعتبر'), ('رنگ سربرگ کروم در موبایل', 'رنگ سربرگ کروم در موبایل')], max_length=50, verbose_name='نام'),
        ),
    ]
