# Generated by Django 3.1 on 2020-10-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201012_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
    ]
