# Generated by Django 3.1 on 2020-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_partialpage_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='app_name',
            field=models.CharField(default='app', max_length=50, verbose_name='app_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='child_class',
            field=models.CharField(default='page', max_length=50, verbose_name='child_class'),
            preserve_default=False,
        ),
    ]
