# Generated by Django 3.1 on 2020-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200928_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='header_image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/OurTeam/Header/', verbose_name='تصویر سربرگ'),
        ),
    ]
