# Generated by Django 3.1 on 2020-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_resume_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subtitle'),
        ),
    ]
