# Generated by Django 3.1 on 2020-09-29 21:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_jumbotron_full_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumbotron',
            name='full_description',
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='شرح کامل html'),
        ),
    ]
