# Generated by Django 3.1 on 2020-09-29 21:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200930_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumbotron',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='شرح کوتاه'),
        ),
    ]
