# Generated by Django 3.1 on 2020-09-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200930_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='app_name',
            field=models.CharField(default='app', max_length=50, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='child_class',
            field=models.CharField(default='page', max_length=50, verbose_name='child_class'),
        ),
    ]
