# Generated by Django 3.1 on 2020-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_homeslider_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('color', models.CharField(max_length=50, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
    ]
