# Generated by Django 3.1 on 2020-10-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.link')),
                ('active', models.BooleanField(default=False, verbose_name='نقشه سایت فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sitemap', verbose_name='نود والد')),
            ],
            bases=('app.link',),
        ),
    ]
