from django.contrib import admin
from .models import *

admin.site.register(Technology)
admin.site.register(CountDownItem)
admin.site.register(Page)
admin.site.register(PartialPage)
admin.site.register(Jumbotron)

admin.site.register(GalleryAlbum)
admin.site.register(GalleryPhoto)
admin.site.register(OurWorkCategory)
admin.site.register(Comment)
admin.site.register(Like)
admin.site.register(Tag)
admin.site.register(Banner)
admin.site.register(Icon)
admin.site.register(OurWork)
admin.site.register(Blog)
admin.site.register(Signature)
admin.site.register(ContactMessage)
admin.site.register(Document)
admin.site.register(FAQ)
admin.site.register(HomeSlider)
admin.site.register(Link)
admin.site.register(MainPic)
admin.site.register(MetaData)
admin.site.register(Profile)
admin.site.register(ProfileTransaction)
admin.site.register(Notification)
admin.site.register(OurTeam)
admin.site.register(OurService)
admin.site.register(Parameter)
admin.site.register(Region)
admin.site.register(Resume)
admin.site.register(ResumeCategory)
admin.site.register(SocialLink)
admin.site.register(Testimonial)
# Register your models here.
