from phoenix import settings

SERVER_ON_PARS=settings.SERVER_ON_PARS
SERVER_ON_HEROKU=settings.SERVER_ON_HEROKU
SERVER_ON_LOCAL=settings.SERVER_ON_LOCAL
REMOTE_MEDIA=settings.REMOTE_MEDIA
SERVER_ON_PARS=settings.SERVER_ON_PARS
DEBUG=settings.DEBUG
BASE_DIR=settings.BASE_DIR
COMING_SOON=settings.COMING_SOON
MYSQL=settings.MYSQL
TIME_ZONE=settings.TIME_ZONE
STATIC_URL=settings.STATIC_URL
STATIC_ROOT=settings.STATIC_ROOT
MEDIA_URL=settings.MEDIA_URL
MEDIA_ROOT=settings.MEDIA_ROOT
SITE_URL=settings.SITE_URL
ADMIN_URL=settings.ADMIN_URL
DOWNLOAD_ROOT=settings.DOWNLOAD_ROOT
PUSHER_IS_ENABLE=settings.PUSHER_IS_ENABLE

CSRF_FAILURE_VIEW = 'app.views.csrf_failure'
SITE_DOMAIN='http://www.imenyar.com'





