# Generated by Django 3.1 on 2020-09-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_auto_20200924_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('پیش فرض', 'پیش فرض'), ('در حال انجام', 'در حال انجام'), ('آماده سازی اولیه', 'آماده سازی اولیه'), ('ششششششش', 'انجام شده'), ('تحویل شده', 'تحویل شده'), ('درحال آنالیز', 'درحال آنالیز')], default='پیش فرض', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='title',
            field=models.CharField(choices=[('حسابداری', 'حسابداری'), ('مدیریت', 'مدیریت'), ('حمل و نقل', 'حمل و نقل'), ('کارپردازی', 'کارپردازی'), ('عمران', 'عمران'), ('تاسیسات', 'تاسیسات'), ('مهندسی', 'مهندسی'), ('برق', 'برق'), ('مکانیک', 'مکانیک')], default='حسابداری', max_length=50, verbose_name='title'),
        ),
    ]
