# Generated by Django 3.1 on 2020-09-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20200924_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('پیش فرض', 'پیش فرض'), ('در حال انجام', 'در حال انجام'), ('آماده سازی اولیه', 'آماده سازی اولیه'), ('انجام شده', 'انجام شده'), ('تحویل شده', 'تحویل شده'), ('درحال آنالیز', 'درحال آنالیز')], default='پیش فرض', max_length=50, verbose_name='status'),
        ),
    ]
