# Generated by Django 3.1 on 2020-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_auto_20200924_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerpage',
            name='related_pages',
            field=models.ManyToManyField(blank=True, to='projectmanager.ManagerPage', verbose_name='related_pages'),
        ),
        migrations.AlterField(
            model_name='managerpage',
            name='posttitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پس عنوان'),
        ),
        migrations.AlterField(
            model_name='managerpage',
            name='pretitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پیش عنوان'),
        ),
    ]
