# Generated by Django 3.1 on 2020-09-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200923_0246'),
        ('projectmanager', '0008_auto_20200924_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelog',
            name='action',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('DELETE', 'DELETE'), ('SAVE', 'SAVE'), ('INITIAL', 'INITIAL')], default='DEFAULT', max_length=50, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='ایجاد کننده'),
        ),
    ]
