# Generated by Django 3.1 on 2020-09-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_auto_20200924_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelog',
            name='manager_page_id',
            field=models.IntegerField(default=0, verbose_name='manager_page_id'),
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.managerpage', verbose_name='page'),
        ),
    ]
