# Generated by Django 3.1 on 2020-09-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_auto_20200924_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projectmanager.workunit', verbose_name='work_unit'),
        ),
    ]
