# Generated by Django 3.1 on 2020-09-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_employee_work_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerpage',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
