# Generated by Django 3.1 on 2020-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0013_auto_20200925_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='workunit',
            name='childs',
            field=models.ManyToManyField(blank=True, to='projectmanager.WorkUnit', verbose_name='زیر مجموعه ها'),
        ),
    ]
