# Generated by Django 3.1 on 2020-09-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0014_workunit_childs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workunit',
            name='childs',
        ),
        migrations.AddField(
            model_name='workunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.workunit', verbose_name='parent'),
        ),
    ]
