# Generated by Django 3.1 on 2020-09-24 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0017_auto_20200925_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='project'),
        ),
    ]
