# Generated by Django 3.1 on 2020-09-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0019_auto_20200925_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('managerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.managerpage')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_name', models.CharField(max_length=50, verbose_name='واحد')),
                ('status', models.CharField(choices=[('پیش فرض', 'پیش فرض'), ('درخواست اولیه', 'درخواست اولیه'), ('پذیرفته شده', 'پذیرفته شده'), ('در حال بررسی', 'در حال بررسی'), ('رد شده', 'رد شده'), ('لغو شده', 'لغو شده')], default='درخواست اولیه', max_length=50, verbose_name='status')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projectmanager.contractor', verbose_name='contractor')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projectmanager.employee', verbose_name='employee')),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.project', verbose_name='project')),
                ('requested_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'MaterialRequest',
                'verbose_name_plural': 'MaterialRequests',
            },
            bases=('projectmanager.managerpage',),
        ),
    ]
