# Generated by Django 3.1 on 2020-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_signature_status'),
        ('projectmanager', '0020_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='signatures',
            field=models.ManyToManyField(blank=True, to='app.Signature', verbose_name='signatures'),
        ),
    ]
