# Generated by Django 3.1 on 2020-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0021_materialrequest_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerpage',
            name='child_class',
            field=models.CharField(default='project', max_length=50, verbose_name='child_class'),
            preserve_default=False,
        ),
    ]
