# Generated by Django 3.1 on 2020-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0022_managerpage_child_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerpage',
            name='child_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='child_class'),
        ),
    ]
