# Generated by Django 3.1 on 2020-09-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0024_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(default='sss', max_length=50, verbose_name='نوع مشکل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issueforwhat', to='projectmanager.managerpage', verbose_name='issue_for'),
        ),
    ]
