# Generated by Django 3.1 on 2020-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0025_auto_20200926_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('FORCE', 'FORCE'), ('DANGER', 'DANGER'), ('EVENT', 'EVENT'), ('WARNING', 'WARNING')], default='DEFAULT', max_length=50, verbose_name='نوع مشکل'),
        ),
    ]
