# Generated by Django 3.1 on 2020-09-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0029_auto_20200926_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerpage',
            old_name='icon_origin',
            new_name='icon',
        ),
    ]
