# Generated by Django 3.1 on 2020-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0033_assignment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments - تکلیف ها'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Contractor', 'verbose_name_plural': 'Contractors - پیمانکار ها'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees - کارکنان'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images - تصویر ها'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Issue', 'verbose_name_plural': 'Issues - مشکلات پیش آمده'},
        ),
        migrations.AlterModelOptions(
            name='managerpage',
            options={'verbose_name': 'ManagerPage', 'verbose_name_plural': 'ManagerPages - صفحات'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials -  متریال ها'},
        ),
        migrations.AlterModelOptions(
            name='materialbrand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands - برند های متریال'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': 'MaterialCategory', 'verbose_name_plural': 'MaterialCategories - دسته بندی های متریال'},
        ),
        migrations.AlterModelOptions(
            name='materiallog',
            options={'verbose_name': 'MaterialLog', 'verbose_name_plural': 'MaterialLogs- لاگ های متریال'},
        ),
        migrations.AlterModelOptions(
            name='materialobject',
            options={'verbose_name': 'MaterialObject', 'verbose_name_plural': 'MaterialObjects- متریال های موجود'},
        ),
        migrations.AlterModelOptions(
            name='materialpackage',
            options={'verbose_name': 'MaterialPackage', 'verbose_name_plural': 'MaterialPackages - پکیج های متریال'},
        ),
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'verbose_name': 'MaterialRequest', 'verbose_name_plural': 'MaterialRequests - درخواست های متریال'},
        ),
        migrations.AlterModelOptions(
            name='materialwarehouse',
            options={'verbose_name': 'MaterialWareHouse', 'verbose_name_plural': 'MaterialWareHouses - انبار های متریال'},
        ),
        migrations.AlterModelOptions(
            name='pagelog',
            options={'verbose_name': 'PageLog', 'verbose_name_plural': 'PageLogs - لاگ های صفحات'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects - پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'ProjectCategory', 'verbose_name_plural': 'ProjectCategories - دسته بندی پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='workunit',
            options={'verbose_name': 'WorkUnit', 'verbose_name_plural': 'WorkUnits - واحد های سازمانی'},
        ),
        migrations.AlterField(
            model_name='materialwarehouse',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='materialwarehouse',
            name='employees',
            field=models.ManyToManyField(blank=True, to='projectmanager.Employee', verbose_name='کارکنان'),
        ),
        migrations.AlterField(
            model_name='materialwarehouse',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='موقعیت'),
        ),
    ]
