# Generated by Django 3.1 on 2020-10-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0034_auto_20201004_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='قفسه')),
                ('col', models.IntegerField(verbose_name='ردیف')),
                ('material_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.materialobject', verbose_name='متریال')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.materialwarehouse', verbose_name='انبار متریال')),
            ],
            options={
                'verbose_name': 'MaterialInStock',
                'verbose_name_plural': 'MaterialInStocks- متریال های موجود در انبار',
            },
        ),
    ]
