# Generated by Django 3.1 on 2020-10-05 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0039_auto_20201005_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinstock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('پیش فرض', 'پیش فرض'), ('درخواست اولیه', 'درخواست اولیه'), ('پذیرفته شده', 'پذیرفته شده'), ('در حال بررسی', 'در حال بررسی'), ('رد شده', 'رد شده'), ('لغو شده', 'لغو شده'), ('تحویل شده', 'تحویل شده')], default='درخواست اولیه', max_length=50, verbose_name='status'),
        ),
    ]
