# Generated by Django 3.1 on 2020-10-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0041_materialinstock_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinstock',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='material',
            name='unit_name',
            field=models.CharField(default='عدد', max_length=50, verbose_name='واحد'),
            preserve_default=False,
        ),
    ]
