# Generated by Django 3.1 on 2020-10-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0042_auto_20201006_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.materialbrand', verbose_name='brand'),
        ),
    ]
