# Generated by Django 3.1 on 2020-10-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0045_materialinstock_date_opi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_for',
        ),
        migrations.AddField(
            model_name='issue',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issueforwhatpage', to='projectmanager.managerpage', verbose_name='issue_for'),
            preserve_default=False,
        ),
    ]
