# Generated by Django 3.1 on 2020-10-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0047_auto_20201008_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerpage',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='managerpage',
            name='parent1',
        ),
        migrations.RemoveField(
            model_name='materialwarehouse',
            name='location',
        ),
        migrations.AddField(
            model_name='managerpage',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='موقعیت در نقشه گوگل'),
        ),
        migrations.AddField(
            model_name='managerpage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent1', to='projectmanager.managerpage', verbose_name='parent'),
        ),
    ]
