# Generated by Django 3.1 on 2020-10-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0052_archivecategory_archivedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.archivecategory', verbose_name='دسته بندی'),
        ),
    ]
