# Generated by Django 3.1 on 2020-09-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('url', models.CharField(blank=True, max_length=1100, null=True, verbose_name='url')),
                ('seen', models.BooleanField(default=False, verbose_name='دیده شد')),
                ('priority', models.IntegerField(default=1000, verbose_name='اولویت')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_seen', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شده')),
                ('icon', models.CharField(default='notification_important', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose')], default='info', max_length=500, null=True, verbose_name='رنگ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engapp.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'اعلان ها',
            },
        ),
    ]
