# Generated by Django 3.1 on 2020-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialpage',
            name='galleries',
            field=models.ManyToManyField(blank=True, to='engapp.GalleryAlbum', verbose_name='گالری ها'),
        ),
    ]
