# Generated by Django 3.1 on 2020-09-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('jumbotron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engapp.jumbotron')),
                ('image_banner', models.ImageField(upload_to='engapp/images/Banner/', verbose_name='تصویر بنر  345*970 ')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'بنر های  ',
            },
            bases=('engapp.jumbotron',),
        ),
        migrations.CreateModel(
            name='CountDownItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_origin', models.ImageField(upload_to='engapp/images/CountDownItem/', verbose_name='تصویر  345*970 ')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('pretitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pre Title')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('counter', models.IntegerField(default=100, verbose_name='شمارنده')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'CountDownItem',
                'verbose_name_plural': 'CountDownItems',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='documents',
            field=models.ManyToManyField(blank=True, to='engapp.Document', verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='page',
            name='links',
            field=models.ManyToManyField(blank=True, to='engapp.Link', verbose_name='links'),
        ),
        migrations.AddField(
            model_name='page',
            name='count_down_items',
            field=models.ManyToManyField(blank=True, to='engapp.CountDownItem', verbose_name='count_down_items'),
        ),
    ]
