# Generated by Django 3.1 on 2020-09-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0002_partialpage_galleries'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Gallery/Thumbnail/', verbose_name='تصویر کوچک '),
        ),
    ]
