# Generated by Django 3.1 on 2020-09-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='grid_image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Page/Grid/', verbose_name='تصویر گرید'),
        ),
    ]
