# Generated by Django 3.1 on 2020-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0003_galleryphoto_thumbnail_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
