# Generated by Django 3.1 on 2020-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0003_page_grid_image_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'ContactMessage', 'verbose_name_plural': 'ContactMessages'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'verbose_name': 'GalleryAlbum', 'verbose_name_plural': 'GalleryAlbums'},
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'GalleryPhoto', 'verbose_name_plural': 'GalleryPhotos'},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'HomeSlider', 'verbose_name_plural': 'HomeSliders'},
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'Icon', 'verbose_name_plural': 'Icons'},
        ),
        migrations.AlterModelOptions(
            name='jumbotron',
            options={'verbose_name': 'Jumbotron', 'verbose_name_plural': 'Jumbotrons'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='mainpic',
            options={'verbose_name': 'MainPic', 'verbose_name_plural': 'MainPics'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'MetaData', 'verbose_name_plural': 'MetaDatas'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='ourservice',
            options={'verbose_name': 'OurService', 'verbose_name_plural': 'OurServices'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'verbose_name': 'OurTeam', 'verbose_name_plural': 'OurTeam'},
        ),
        migrations.AlterModelOptions(
            name='ourwork',
            options={'verbose_name': 'OurWork', 'verbose_name_plural': 'OurWorks'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterModelOptions(
            name='partialpage',
            options={'verbose_name': 'PartialPage', 'verbose_name_plural': 'PartialPages'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='resumecategory',
            options={'verbose_name': 'ResumeCategory', 'verbose_name_plural': 'ResumeCategorys'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'SocialLink', 'verbose_name_plural': 'SocialLinks'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='mainpic',
            name='name',
            field=models.CharField(choices=[('CAROUSEL', 'CAROUSEL'), ('FAQ', 'FAQ'), ('SEARCH', 'SEARCH'), ('VIDEO', 'VIDEO'), ('ABOUT', 'ABOUT'), ('CONTACT_HEADER', 'CONTACT_HEADER'), ('LOGO', 'LOGO'), ('BLOG_HEADER', 'BLOG_HEADER'), ('OUR_WORK_HEADER', 'OUR_WORK_HEADER'), ('PAGE_HEADER_DEFAULT', 'PAGE_HEADER_DEFAULT'), ('TAG_HEADER', 'TAG_HEADER'), ('ABOUT_HEADER', 'ABOUT_HEADER')], max_length=50, verbose_name='جای تصویر'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('ABOUT_US_SHORT', 'ABOUT_US_SHORT'), ('ABOUT_US', 'ABOUT_US'), ('MOBILE', 'MOBILE'), ('URL', 'URL'), ('EMAIL', 'EMAIL'), ('FAX', 'FAX'), ('TEL', 'TEL'), ('LOCATION', 'LOCATION'), ('ADDRESS', 'ADDRESS'), ('SLOGAN', 'SLOGAN'), ('ABOUT_US_TITLE', 'ABOUT_US_TITLE'), ('TITLE', 'TITLE'), ('CURRENCY', 'CURRENCY'), ('PRE_TILTE', 'PRE_TILTE'), ('VIDEO_TITLE', 'VIDEO_TITLE'), ('VIDEO_LINK', 'VIDEO_LINK'), ('CONTACT_US', 'CONTACT_US'), ('POSTAL_CODE', 'POSTAL_CODE'), ('TERMS', 'TERMS'), ('OUR_TEAM_TITLE', 'OUR_TEAM_TITLE'), ('OUR_TEAM_LINK', 'OUR_TEAM_LINK'), ('CSRF_FAILURE_MESSAGE', 'CSRF_FAILURE_MESSAGE'), ('THEME_COLOR', 'THEME_COLOR')], max_length=50, verbose_name='نام'),
        ),
    ]
