# Generated by Django 3.1 on 2020-09-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0003_auto_20200918_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpic',
            name='name',
            field=models.CharField(choices=[('CAROUSEL', 'CAROUSEL'), ('FAQ', 'FAQ'), ('SEARCH', 'SEARCH'), ('VIDEO', 'VIDEO'), ('ABOUT', 'ABOUT'), ('CONTACT_HEADER', 'CONTACT_HEADER'), ('LOADING', 'LOADING'), ('LOGO', 'LOGO'), ('BIG_LOGO', 'BIG_LOGO'), ('DARK_LOGO', 'DARK_LOGO'), ('LIGHT_LOGO', 'LIGHT_LOGO'), ('BLOG_HEADER', 'BLOG_HEADER'), ('OUR_WORK_HEADER', 'OUR_WORK_HEADER'), ('PAGE_HEADER_DEFAULT', 'PAGE_HEADER_DEFAULT'), ('TAG_HEADER', 'TAG_HEADER'), ('ABOUT_HEADER', 'ABOUT_HEADER')], max_length=50, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.CharField(default='--', max_length=2000, verbose_name='Body'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='footer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Title'),
        ),
    ]
