# Generated by Django 3.1 on 2020-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0004_auto_20200918_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('ABOUT_US_SHORT', 'ABOUT_US_SHORT'), ('ABOUT_US_TITLE', 'ABOUT_US_TITLE'), ('ADDRESS', 'ADDRESS'), ('ABOUT_US', 'ABOUT_US'), ('CONTACT_US', 'CONTACT_US'), ('CONTACT_US_TITLE', 'CONTACT_US_TITLE'), ('CSRF_FAILURE_MESSAGE', 'CSRF_FAILURE_MESSAGE'), ('CURRENCY', 'CURRENCY'), ('FAX', 'FAX'), ('EMAIL', 'EMAIL'), ('LOCATION', 'LOCATION'), ('MOBILE', 'MOBILE'), ('OUR_TEAM_LINK', 'OUR_TEAM_LINK'), ('OUR_TEAM_TITLE', 'OUR_TEAM_TITLE'), ('POSTAL_CODE', 'POSTAL_CODE'), ('PRE_TILTE', 'PRE_TILTE'), ('SINCE', 'SINCE'), ('SLOGAN', 'SLOGAN'), ('TEL', 'TEL'), ('TERMS', 'TERMS'), ('THEME_COLOR', 'THEME_COLOR'), ('TITLE', 'TITLE'), ('URL', 'URL'), ('VIDEO_LINK', 'VIDEO_LINK'), ('VIDEO_TITLE', 'VIDEO_TITLE')], max_length=50, verbose_name='Parameter Name'),
        ),
    ]
