# Generated by Django 3.1 on 2020-09-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0004_ourteam_for_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive?'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_banner',
            field=models.ImageField(upload_to='engapp/images/Banner/', verbose_name='Big Image 345*970 '),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engapp.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replys',
            field=models.ManyToManyField(blank=True, to='engapp.Comment', verbose_name='Replies'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(max_length=50, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='engapp/images/Document', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engapp.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=5000, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose')], default='primary', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='icon',
            field=models.CharField(choices=[('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('chat', 'chat'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('face', 'face'), ('favorite', 'favorite'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('notification_important', 'notification_important'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('vpn_key', 'vpn_key')], default='help_outline', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='priority',
            field=models.IntegerField(verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='photos',
            field=models.ManyToManyField(blank=True, to='engapp.GalleryPhoto', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Gallery/Thumbnail/', verbose_name='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image_banner',
            field=models.ImageField(upload_to='engapp/images/Banner/', verbose_name='Image 1333*2000 '),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='tag_number',
            field=models.IntegerField(default=100, verbose_name='Tag Number'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='tag_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag Text'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose')], default='primary', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='height',
            field=models.IntegerField(default=128, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon FontAwesome'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_material',
            field=models.CharField(blank=True, choices=[('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('chat', 'chat'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('face', 'face'), ('favorite', 'favorite'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('notification_important', 'notification_important'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('vpn_key', 'vpn_key')], max_length=100, null=True, verbose_name='Icon Material'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_svg',
            field=models.TextField(blank=True, null=True, verbose_name='Icon svg'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/OurService/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='width',
            field=models.IntegerField(default=128, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='action_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Button Link URL'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='posttitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='pretitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pre Title'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='video_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Video Text'),
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='video_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Video Link URL'),
        ),
        migrations.AlterField(
            model_name='like',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engapp.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='link',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='link',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='mainpic',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/MainPic/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mainpic',
            name='name',
            field=models.CharField(choices=[('CAROUSEL', 'CAROUSEL'), ('FAQ', 'FAQ'), ('SEARCH', 'SEARCH'), ('VIDEO', 'VIDEO'), ('ABOUT', 'ABOUT'), ('CONTACT_HEADER', 'CONTACT_HEADER'), ('LOGO', 'LOGO'), ('BLOG_HEADER', 'BLOG_HEADER'), ('OUR_WORK_HEADER', 'OUR_WORK_HEADER'), ('PAGE_HEADER_DEFAULT', 'PAGE_HEADER_DEFAULT'), ('TAG_HEADER', 'TAG_HEADER'), ('ABOUT_HEADER', 'ABOUT_HEADER')], max_length=50, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='color',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose')], default='info', max_length=500, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Seen'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='notification_important', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Seen?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose')], default='primary', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='height',
            field=models.IntegerField(default=128, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='icon_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon FontAwesome'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='icon_material',
            field=models.CharField(blank=True, choices=[('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('chat', 'chat'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('face', 'face'), ('favorite', 'favorite'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('notification_important', 'notification_important'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('vpn_key', 'vpn_key')], max_length=100, null=True, verbose_name='Icon Material'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='icon_svg',
            field=models.TextField(blank=True, null=True, verbose_name='Icon svg'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='width',
            field=models.IntegerField(default=128, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='image_origin',
            field=models.ImageField(upload_to='engapp/images/OurTeam/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='job',
            field=models.CharField(max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Map Location 400*400'),
        ),
        migrations.AlterField(
            model_name='page',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='comments',
            field=models.ManyToManyField(blank=True, to='engapp.Comment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='page',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description_secondary',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Secondary Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='documents',
            field=models.ManyToManyField(blank=True, to='engapp.Document', verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='page',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='page',
            name='grid_image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Page/Grid/', verbose_name='Grid Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Page/Banner/', verbose_name='Header Image 345*970 '),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Page/', verbose_name='Big Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='likes',
            field=models.ManyToManyField(blank=True, to='engapp.Like', verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='page',
            name='links',
            field=models.ManyToManyField(blank=True, to='engapp.Link', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_datas',
            field=models.ManyToManyField(blank=True, to='engapp.MetaData', verbose_name='Meta Datas'),
        ),
        migrations.AlterField(
            model_name='page',
            name='partials',
            field=models.ManyToManyField(blank=True, to='engapp.PartialPage', verbose_name='Partial Pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='page',
            name='relateds',
            field=models.ManyToManyField(blank=True, to='engapp.Page', verbose_name='Related Pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, to='engapp.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Page/thumbnail/', verbose_name='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_secondary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Secondary Title'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('ABOUT_US_SHORT', 'ABOUT_US_SHORT'), ('ABOUT_US', 'ABOUT_US'), ('MOBILE', 'MOBILE'), ('URL', 'URL'), ('EMAIL', 'EMAIL'), ('FAX', 'FAX'), ('TEL', 'TEL'), ('LOCATION', 'LOCATION'), ('ADDRESS', 'ADDRESS'), ('SLOGAN', 'SLOGAN'), ('ABOUT_US_TITLE', 'ABOUT_US_TITLE'), ('TITLE', 'TITLE'), ('CURRENCY', 'CURRENCY'), ('PRE_TILTE', 'PRE_TILTE'), ('VIDEO_TITLE', 'VIDEO_TITLE'), ('VIDEO_LINK', 'VIDEO_LINK'), ('CONTACT_US', 'CONTACT_US'), ('POSTAL_CODE', 'POSTAL_CODE'), ('TERMS', 'TERMS'), ('OUR_TEAM_TITLE', 'OUR_TEAM_TITLE'), ('OUR_TEAM_LINK', 'OUR_TEAM_LINK'), ('CSRF_FAILURE_MESSAGE', 'CSRF_FAILURE_MESSAGE'), ('THEME_COLOR', 'THEME_COLOR')], max_length=50, verbose_name='Parameter Name'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=10000, verbose_name='Parameter Value'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Added'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='description',
            field=models.TextField(verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='documents',
            field=models.ManyToManyField(blank=True, to='engapp.Document', verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='galleries',
            field=models.ManyToManyField(blank=True, to='engapp.GalleryAlbum', verbose_name='Gallery Albums'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Blog/Partials/', verbose_name='Big Image'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='links',
            field=models.ManyToManyField(blank=True, to='engapp.Link', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='posttitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='pretitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pre Title'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='partialpage',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_origin',
            field=models.ImageField(blank=True, max_length=1200, null=True, upload_to='engapp/images/Profile/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('IRAN', 'IRAN'), ('EUROPE', 'EUROPE'), ('AMERICA', 'AMERICA'), ('ASIA', 'ASIA')], default='IRAN', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='resumecategory',
            name='title',
            field=models.CharField(choices=[('EXPERIENCE', 'EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('SKILLS', 'SKILLS'), ('INTERESTS', 'INTERESTS'), ('CERTIFICATIONS', 'CERTIFICATIONS'), ('AWARDS', 'AWARDS'), ('WORKS DONE', 'WORKS DONE')], default='EDUCATION', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose')], default='primary', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='height',
            field=models.IntegerField(default=128, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon FontAwesome'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_material',
            field=models.CharField(blank=True, choices=[('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('chat', 'chat'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('face', 'face'), ('favorite', 'favorite'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('notification_important', 'notification_important'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('vpn_key', 'vpn_key')], max_length=100, null=True, verbose_name='Icon Material'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_svg',
            field=models.TextField(blank=True, null=True, verbose_name='Icon svg'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/OurService/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='width',
            field=models.IntegerField(default=128, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engapp.icon', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Tag/', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='footer',
            field=models.CharField(max_length=200, verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='engapp/images/Testimonial/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='engapp.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='Title'),
        ),
    ]
