# Generated by Django 3.1 on 2020-09-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0005_auto_20200920_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpic',
            name='name',
            field=models.CharField(choices=[('FAVICON', 'FAVICON'), ('CAROUSEL', 'CAROUSEL'), ('FAQ', 'FAQ'), ('SEARCH', 'SEARCH'), ('VIDEO', 'VIDEO'), ('ABOUT', 'ABOUT'), ('CONTACT_HEADER', 'CONTACT_HEADER'), ('LOADING', 'LOADING'), ('LOGO', 'LOGO'), ('BIG_LOGO', 'BIG_LOGO'), ('DARK_LOGO', 'DARK_LOGO'), ('LIGHT_LOGO', 'LIGHT_LOGO'), ('BLOG_HEADER', 'BLOG_HEADER'), ('OUR_WORK_HEADER', 'OUR_WORK_HEADER'), ('PAGE_HEADER_DEFAULT', 'PAGE_HEADER_DEFAULT'), ('TAG_HEADER', 'TAG_HEADER'), ('ABOUT_HEADER', 'ABOUT_HEADER')], max_length=50, verbose_name='Image Title'),
        ),
    ]
