# Generated by Django 3.1 on 2020-09-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0006_auto_20200920_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, verbose_name='Priority')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='engapp/images/OurWorkCategory/', verbose_name='Header Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'OurWorkCategory',
                'verbose_name_plural': 'OurWorkCategories',
            },
        ),
        migrations.AddField(
            model_name='ourwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engapp.ourworkcategory', verbose_name='Category'),
        ),
    ]
