# Generated by Django 3.1 on 2020-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0007_auto_20200920_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='lname',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='_', max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
