# Generated by Django 3.1 on 2020-09-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200918_0237'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workunit',
            name='agents',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.employee', verbose_name='employee'),
        ),
        migrations.AddField(
            model_name='workunit',
            name='employees',
            field=models.ManyToManyField(blank=True, to='market.Employee', verbose_name='نیروی انسانی'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.productunit', verbose_name='product_unit'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='work_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.workunit', verbose_name='واحد سازمانی'),
        ),
    ]
