# Generated by Django 3.1 on 2020-09-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20200918_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'Letter', 'verbose_name_plural': 'نامه ها'},
        ),
        migrations.AlterModelOptions(
            name='lettersignature',
            options={'verbose_name': 'LetterSignature', 'verbose_name_plural': 'امضا های نامه ها'},
        ),
        migrations.AlterModelOptions(
            name='productrequest',
            options={'verbose_name': 'ProductRequest', 'verbose_name_plural': 'درخواست های خرید'},
        ),
        migrations.AlterModelOptions(
            name='productrequestsignature',
            options={'verbose_name': 'ProductRequestSignature', 'verbose_name_plural': 'امضاهای درخواست های خرید'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='purchaseagent',
            options={'verbose_name': 'PurchaseAgent', 'verbose_name_plural': 'مسئول های خرید'},
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
