# Generated by Django 3.1 on 2020-09-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20200920_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'Letter', 'verbose_name_plural': 'Lettes - نامه ها'},
        ),
        migrations.AlterModelOptions(
            name='lettersignature',
            options={'verbose_name': 'LetterSignature', 'verbose_name_plural': 'LetterSignatures - امضا های نامه ها'},
        ),
        migrations.AlterModelOptions(
            name='productrequest',
            options={'verbose_name': 'ProductRequest', 'verbose_name_plural': 'ProductRequests -درخواست های خرید'},
        ),
        migrations.AlterModelOptions(
            name='productrequestsignature',
            options={'verbose_name': 'ProductRequestSignature', 'verbose_name_plural': 'ProductRequestSignatures -امضاهای درخواست های خرید'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects - پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='purchaseagent',
            options={'verbose_name': 'PurchaseAgent', 'verbose_name_plural': 'PurchaseAgents - مسئول های خرید'},
        ),
        migrations.AlterModelOptions(
            name='workunit',
            options={'verbose_name': 'WorkUnit', 'verbose_name_plural': 'WorkUnits - واحد های سازمانی'},
        ),
        migrations.AddField(
            model_name='workunit',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
    ]
