# Generated by Django 3.1 on 2020-09-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200922_0912'),
        ('automation', '0004_auto_20200920_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('نگهبان', 'نگهبان'), ('مدیر', 'مدیر'), ('فنی', 'فنی'), ('تایید نشده', 'تایید نشده'), ('حسابدار', 'حسابدار'), ('صندوقدار', 'صندوقدار')], default='تایید نشده', max_length=50, verbose_name='نقش')),
                ('degree', models.CharField(choices=[('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], default='کارشناسی', max_length=50, verbose_name='مدرک')),
                ('major', models.CharField(blank=True, max_length=50, null=True, verbose_name='رشته تحصیلی')),
                ('introducer', models.CharField(blank=True, max_length=50, null=True, verbose_name='معرف')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_id', to='app.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.AlterField(
            model_name='workunit',
            name='employees',
            field=models.ManyToManyField(blank=True, to='automation.Employee', verbose_name='نیروی انسانی'),
        ),
    ]
