# Generated by Django 3.1 on 2020-09-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_auto_20200923_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='PusherBeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('instance_id', models.CharField(max_length=100, verbose_name='instanse_id')),
                ('authorization', models.CharField(max_length=200, verbose_name='authorization')),
            ],
            options={
                'verbose_name': 'PusherBeam',
                'verbose_name_plural': 'PusherBeams',
            },
        ),
        migrations.CreateModel(
            name='PusherChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(choices=[('NONE', 'NONE'), ('SHIP', 'SHIP'), ('DELIVER', 'DELIVER'), ('PACK', 'PACK'), ('SYNC', 'SYNC'), ('SUBMIT', 'SUBMIT'), ('NOTIFICATION', 'NOTIFICATION')], default='NONE', max_length=20, verbose_name='channel_name')),
                ('app_id', models.CharField(max_length=20, verbose_name='app_id')),
                ('key', models.CharField(max_length=50, verbose_name='key')),
                ('secret', models.CharField(max_length=50, verbose_name='secret')),
                ('cluster', models.CharField(default='us2', max_length=20, verbose_name='cluster')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='PusherChannelEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('event_name', models.CharField(max_length=50, verbose_name='event')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopusher.pusherchannel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'ChannelEvent',
                'verbose_name_plural': 'ChannelEvents',
            },
        ),
        migrations.CreateModel(
            name='PusherBeamInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50, verbose_name='interest')),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopusher.pusherbeam', verbose_name='beam')),
            ],
            options={
                'verbose_name': 'PusherBeamInterest',
                'verbose_name_plural': 'PusherBeamInterests',
            },
        ),
        migrations.CreateModel(
            name='ProfileChannelEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopusher.pusherchannelevent', verbose_name='channel_event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'ProfileChannelEvent',
                'verbose_name_plural': 'ProfileChannelEvents',
            },
        ),
    ]
