# Generated by Django 3.1 on 2020-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leopusher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pusherchannel',
            name='channel_name',
            field=models.CharField(max_length=20, verbose_name='channel_name'),
        ),
    ]
