# Generated by Django 3.1 on 2020-09-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_auto_20200920_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام بانک')),
                ('branch', models.CharField(max_length=50, verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='CurrentFeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='دسته بندی هزینه های جاری')),
            ],
            options={
                'verbose_name': 'CurrentFeeCategory',
                'verbose_name_plural': 'CurrentFeeCategorys',
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'FinancialAccount',
                'verbose_name_plural': 'حساب های مالی',
            },
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('date_document', models.DateTimeField(verbose_name='تاریخ سند')),
            ],
            options={
                'verbose_name': 'FinancialDocument',
                'verbose_name_plural': 'اسناد مالی',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('financialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialaccount')),
            ],
            options={
                'verbose_name': 'Cash',
                'verbose_name_plural': 'Cashs',
            },
            bases=('accounting.financialaccount',),
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1399, verbose_name='سال مالی')),
                ('documents', models.ManyToManyField(blank=True, to='accounting.FinancialDocument', verbose_name='اسناد مالی')),
            ],
            options={
                'verbose_name': 'FinancialYear',
                'verbose_name_plural': 'FinancialYears',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('card_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت')),
                ('shaba_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبا')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bank', verbose_name='بانک')),
            ],
            options={
                'verbose_name': 'BankAccount',
                'verbose_name_plural': 'BankAccounts',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('financialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialdocument')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='accounting.financialaccount', verbose_name='از')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='accounting.financialaccount', verbose_name='به')),
            ],
            options={
                'verbose_name': 'FinancialTransaction',
                'verbose_name_plural': 'FinancialTransactions',
            },
            bases=('accounting.financialdocument',),
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('financialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialaccount')),
                ('bank_accounts', models.ManyToManyField(blank=True, to='accounting.BankAccount', verbose_name='حساب های بانکی')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'FinancialProfile',
                'verbose_name_plural': 'FinancialProfiles',
            },
            bases=('accounting.financialaccount',),
        ),
        migrations.CreateModel(
            name='CurrentFee',
            fields=[
                ('financialdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialdocument')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currentfeecategory', verbose_name='دسته بندی هزینه های جاری')),
            ],
            options={
                'verbose_name': 'CurrentFee',
                'verbose_name_plural': 'هزینه های جاری',
            },
            bases=('accounting.financialdocument',),
        ),
    ]
