# Generated by Django 3.1 on 2020-09-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200920_0550'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'بانک ها'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'BankAccount', 'verbose_name_plural': 'حساب های بانکی'},
        ),
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': 'Cash', 'verbose_name_plural': 'صندوق ها'},
        ),
        migrations.AlterModelOptions(
            name='currentfeecategory',
            options={'verbose_name': 'CurrentFeeCategory', 'verbose_name_plural': 'دسته بندی های هزینه های جاری'},
        ),
        migrations.AlterModelOptions(
            name='financialprofile',
            options={'verbose_name': 'FinancialProfile', 'verbose_name_plural': 'پروفایل ها مالی'},
        ),
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'verbose_name': 'FinancialTransaction', 'verbose_name_plural': 'تراکنش های مالی'},
        ),
        migrations.AlterModelOptions(
            name='financialyear',
            options={'verbose_name': 'FinancialYear', 'verbose_name_plural': 'سال های مالی'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.profile', verbose_name='صاحب حساب'),
        ),
    ]
