# Generated by Django 3.1 on 2020-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200920_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialprofile',
            options={'verbose_name': 'FinancialProfile', 'verbose_name_plural': 'پروفایل های مالی'},
        ),
        migrations.AddField(
            model_name='financialyear',
            name='title',
            field=models.CharField(default='_', max_length=50, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
