# Generated by Django 3.1 on 2020-09-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200921_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounting.financialyear', verbose_name='سال مالی'),
            preserve_default=False,
        ),
    ]
