# Generated by Django 3.1 on 2020-09-20 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_financialdocument_financial_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='دسته بندی سند های مالی')),
            ],
            options={
                'verbose_name': 'FinancialDocumentCategory',
                'verbose_name_plural': 'دسته بندی های سند های مالی',
            },
        ),
        migrations.RenameField(
            model_name='currentfee',
            old_name='category',
            new_name='fee_category',
        ),
        migrations.RenameField(
            model_name='currentfeecategory',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.financialdocumentcategory', verbose_name='دسته بندی'),
        ),
    ]
