# Generated by Django 3.1 on 2020-09-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200920_0550'),
        ('accounting', '0006_auto_20200921_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='documents',
            field=models.ManyToManyField(blank=True, to='app.Document', verbose_name='فایل ها'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='links',
            field=models.ManyToManyField(blank=True, to='app.Link', verbose_name='لینک ها'),
        ),
    ]
