# Generated by Django 3.1 on 2020-09-23 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('vehicle_type', models.CharField(choices=[('وانت', 'وانت'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('گریدر', 'گریدر'), ('لودر', 'لودر'), ('تریلی', 'تریلی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور')], default='تاکسی', max_length=50, verbose_name='نوع وسیله ')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_needed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_needed')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'RequestService',
                'verbose_name_plural': 'RequestServices',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('وانت', 'وانت'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('گریدر', 'گریدر'), ('لودر', 'لودر'), ('تریلی', 'تریلی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور')], default='تاکسی', max_length=50, verbose_name='نوع وسیله ')),
                ('brand', models.CharField(choices=[('تویوتا', 'تویوتا'), ('بنز', 'بنز'), ('اسکانیا', 'اسکانیا'), ('ولوو', 'ولوو'), ('کاترپیلار', 'کاترپیلار'), ('هیوندای', 'هیوندای'), ('هووو', 'هووو'), ('دانگ فنگ', 'دانگ فنگ'), ('سایپا', 'سایپا'), ('ایران خودرو', 'ایران خودرو'), ('XCMG', 'XCMG')], default='تویوتا', max_length=50, verbose_name='برند')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('color', models.CharField(choices=[('سفید', 'سفید'), ('سیاه', 'سیاه'), ('نوک مدادی', 'نوک مدادی'), ('دلفینی', 'دلفینی'), ('بژ', 'بژ'), ('قرمز', 'قرمز')], default='سفید', max_length=50, verbose_name='رنگ')),
                ('year', models.IntegerField(verbose_name='year')),
                ('plaque', models.CharField(max_length=50, verbose_name='پلاک')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='مالک')),
                ('driver', models.CharField(blank=True, max_length=50, null=True, verbose_name='راننده')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
